services:
  lapis:
    restart: always
    build: .
    volumes:
      - ./:/code:ro
      - ./dbs:/dbs
      - ./k1_dbs:/code/k1_dbs
      - ./nginx:/nginx
      - ./log:/log
      - ${DATADIR}/merged/topics:/topics
      - ${DATADIR}/tmp:/tmp
      - ${DATADIR}/chatsData:/tmp/chats
      - ${DATADIR}/apps:/apps
    ports:
      - 6510:80
      - 6511:81
      - 64920:64920
    env_file:
      - .env

