services:
  lapis:
    restart: always
    build: .
    volumes:
      - /mnt/4-2/lapis/merged/topics:/topics
      - ./:/code:ro
      - /mnt/4-2/lapis/tmp:/tmp
      - /mnt/4-2/lapis/chatsData:/tmp/chats
    ports:
      - 6510:80

