#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")"

lapis="/mnt/4-2/lapis"
sudo mount -t overlay overlay -o lowerdir="${lapis}/lower",upperdir="${lapis}/upper",workdir="${lapis}/work" "${lapis}/merged"
# fuse-overlayfs -o lowerdir="${lapis}/lower",upperdir="${lapis}/upper",workdir="${lapis}/work" "${lapis}/merged"


