#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")"
docker compose down

lapis="/mnt/4-2/lapis"
sudo umount "${lapis}/merged"
# fusermount -u "${lapis}/merged"

rm -rf "${lapis}/work" "${lapis}/merged"
mkdir -p "${lapis}/upper" "${lapis}/work" "${lapis}/merged"
cp -r "${lapis}/lower" "${lapis}/lower.bak"
sudo overlay merge -l "${lapis}/lower" -u "${lapis}/upper" -f # from https://github.com/kmxz/overlayfs-tools

sudo mount -t overlay overlay -o lowerdir="${lapis}/lower",upperdir="${lapis}/upper",workdir="${lapis}/work" "${lapis}/merged"
# fuse-overlayfs -o lowerdir="${lapis}/lower",upperdir="${lapis}/upper",workdir="${lapis}/work" "${lapis}/merged"

docker compose up -d
