#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")"
lapis="/mnt/4-2/lapis"

# cp -r "${lapis}/lower" "${lapis}/lower.bak"
sudo overlay merge -l "${lapis}/lower" -u "${lapis}/upper" -f # from https://github.com/kmxz/overlayfs-tools

